### ISSUE TITLE
Note title

### ISSUE THREAD

**Issue by DutchPete** [ceciliamay/obsidianmd-theme-primary#45] opened 2022-01-13 08:41 UTC
I am not sure how it happens, but sometimes the note title shifts up a bit making it only half visible. To correct it, I place my cursor anywhere in the middle of the note title (so, not at the end of it) and hit the down arrow. I have not seen this happening in any other theme I tried.

![note-title](https://user-images.githubusercontent.com/10794265/149296426-df6f3fdd-e0a3-41b5-9f83-1caa4e366ff5.gif)

**Comment by ceciliamay** [comment] 2022-01-13 17:21
hmmm i have never experienced this, and to be honest have no idea where to start. could you try updating the theme? there were weird issues in the past that got fixed just by pressing update (even though there aren't any updates). let me know if this still occurs, and i'll try checking with other users!

**Comment by ScottKillen** [comment] 2022-01-13 17:43
I have not experienced this, either.

**Comment by DutchPete** [comment] 2022-01-13 17:50
@ceciliamay it is not a big deal, just a minor annoyance that I can live with. Don't try to solve it, you undoubtedly have more important theme matters to attend to. I just reported it for the record, in case there are others who report it.
Thanks for a great theme.

**Comment by ceciliamay** [comment] 2022-02-03 12:03
Hello @DutchPete !! Are you still experiencing this issue? If yes, what measures have you taken to try to troubleshoot this? If you are not experiencing this anymore, can we close this issue?

**Comment by DutchPete** [comment] 2022-02-03 17:36
Hi @ceciliamay, thanks for checking back on this. Although I have not taken any corrective measures, I have not seen this of late, so please go ahead and close it. If it recurs I'll be in touch.

Many thanks for your help, understanding, and esp. your kindness.

**Closed** 2022-02-03 17:39 UTC

**Comment by Barthcbb** [comment] 2022-06-04 06:35
> I am not sure how it happens…

Although this issue is closed here, I think I can add something about its source: @DutchPete were you by any chance using the [Typewriter Scroll plugin](https://github.com/deathau/cm-typewriter-scroll-obsidian) when the issue occurred?

I managed to reproduce it with the plugin activated. Here's how you I achieved it:
[Video version here.](https://imgur.com/a/XUlJ5xt)

1. Have a multi-panel vertical setting
2. Create a new note on the bottom right panel with CMD+N
3. Hit enter with the title & start typing in the body
4. The panels on the top shift up

So being able to reproduce it, I think it's safe to say the culprit could be the plugin. The issue doesn't happen with the plugin deactivated.

**Comment by DutchPete** [comment] 2022-06-05 01:59
@Barthcbb nope, I was not using the Typewriter Scroll plug-in.

**Comment by Barthcbb** [comment] 2022-06-09 17:08
@DutchPete I managed to reproduce the glitch **without** the plugin, but in a different way.

[Video version here](https://imgur.com/ZV45igr).
1. Use Reading Mode and perform a search (CTRL/CMD + F) for a letter/word somewhere at the bottom of the note
2. The title pane shifts up with the search

Looks like it's an issue with actions that move notes "abruptly" so to speak.

**Comment by DutchPete** [comment] 2022-06-09 17:14
@Barthcbb yep, that's exactly what I meant. With me, though, it happened in Live Preview.
Looks like it is a bit of a challenge for @ceciliamay to figure.
