### ISSUE TITLE
Misaligned "Create Note" Icon in Quick Switcher

### ISSUE THREAD

**Issue by Signynt** [ceciliamay/obsidianmd-theme-primary#58] opened 2022-01-28 16:08 UTC
![image](https://user-images.githubusercontent.com/67801159/151581288-4ed59b93-e15f-4f43-b57d-b061ddb7bb69.png)

**Comment by maxhot** [comment] 2022-01-30 03:18
Looks like duplicate of #48

**Comment by ceciliamay** [comment] 2022-01-30 07:34
This will be fixed early next week!! Hold on guys ;)

**Comment by Signynt** [comment] 2022-01-30 08:12
Oops, didn't see that issue!

**Closed** 2022-02-03 08:52 UTC

**Comment by ceciliamay** [comment] 2022-02-03 11:32
Fixed this in [v.1.1](https://github.com/ceciliamay/obsidianmd-theme-primary/releases/tag/v.1.1.0)! Please update! ✨
